### ISSUE TITLE
Distributed Transaction

### ISSUE THREAD

**Issue by goxiaoy** [go-saas/kit#19]
Event and Local Transaction

**Comment by Goxiaoy** [comment]
**outbox pattern**
https://microservices.io/patterns/data/transactional-outbox.html

for golang:
https://github.com/obsidiandynamics/goharvest
https://github.com/italolelis/outboxer

**Comment by Goxiaoy** [comment]
**Rabbit MQ**
![image](https://user-images.githubusercontent.com/8577611/175822764-d0adac9f-25d5-418a-8a9f-f6feb5255bc0.png)

**Comment by Goxiaoy** [comment]
sagas, tcc, xa, 2-phase message

Golang:
https://github.com/opentrx/seata-golang
https://github.com/dtm-labs/dtm

**Comment by Goxiaoy** [comment]
CDC like 
https://github.com/alibaba/canal
